spring.application.name=paymentservice-merezh
server.port=8084

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health, info
management.endpoint.health.group.liveness.include=livenessState, ping
management.endpoint.health.group.readiness.include=readinessState, db
management.health.diskspace.enabled=false

spring.datasource.url=jdbc:postgresql://postgres-paymentservice:5432/paymentservice-merezh
spring.datasource.username=postgres
spring.datasource.password=postgres123

service.wallets.url=http://walletservice-merezh:8083/api/v1/wallets
service.orders.url=http://orderservice-merezh:8085/api/v1/orders

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update